version: "2"
services:
  docIO:
    restart: always
    image: nginx
    container_name: docIO
    volumes:
      - "./dist:/usr/share/nginx/html:ro"
      - "./sample-website.conf:/etc/nginx/conf.d/sample-website.conf"
    environment:
      - VIRTUAL_HOST=doc.14159.ninja
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=doc.14159.ninja
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: root_default
