version: "2"
services:
  docio:
    restart: always
    container_name: doc-romain
    build: .
    environment:
      - VIRTUAL_HOST=doc.14159.ninja
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=doc.14159.ninja
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: root_default
